### ISSUE TITLE
Slow performance on mobile devices

### ISSUE THREAD

**Issue by daviddelahoz** [kni-labs/rrssb#82] opened 2015-03-13 04:10 UTC
Using this plugin in one of my projects I discovered a problem with the jQuery(window).resize, the performance its affected because this callback seems like its continued called in mobile devices while scrolling or swiping the screen. By the moment I solved the problem commenting this part of the code.

**Comment by aicarlson** [comment] 2015-03-28 21:02
What mobile browsers/devices have you noticed this on? I haven't seen it on iOS or Android and there isn't anything in the code to support the callback being called on scroll.

**Comment by dbox** [comment] 2015-04-13 15:56
Anyone else able to reproduce?

**Comment by daviddelahoz** [comment] 2015-04-15 23:37
Sorry, I didn't mention the slow performance occurs per example when I have some posts and them have the social buttons. Its like if I put the RRSSB bar repeated and that affect the page performance on the device. 

Tested on iOS.

**Comment by dbox** [comment] 2015-04-16 00:54
Can you post an example page?

**Comment by dbox** [comment] 2015-05-03 05:07
Closing due to inactivity

**Comment by daviddelahoz** [comment] 2015-05-29 23:59
here is : http://daviddelahoz.com/rrssb.html just try to resize the browser and you will see the slow performance.

**Comment by dbox** [comment] 2015-05-30 01:39
I first opened this on my phone and didn't see any performance issues. Resizing the browser is a little sluggish, yes. 

Are you having phone performance issues with this page? What device?

**Comment by daviddelahoz** [comment] 2015-05-30 09:23
Iphone 5 with iOS 8, just rotate the phone and try to swipe up or down immediately the Web page and you will see the page feezes until the rrssb finish the resize process

**Comment by connorwyatt** [comment] 2015-05-30 09:27
It's clearly an issue with processing the sizes, as there are about 5 functions that are called sequentially.

Maybe we need to update the sizing mechanisms for v2 @dbox ?

**Comment by dbox** [comment] 2015-05-30 12:57
@connorwyatt, yes, definitely up for any improvements that you can suggest. 

But we can't sacrifice any of the core functionality (aka buttons switching to small size as needed)

Having tons of instances of rrssb on a page wasn't one of my original intents, but would be nice to support it if possible.

**Comment by connorwyatt** [comment] 2015-05-30 12:59
Yeah I agree that the sizing is visually great and I would hope we can keep that like that.

@daviddelahoz How does it respond when there is only one on a page?

**Comment by dbox** [comment] 2015-05-30 13:10
Also what happens when you rotate phone then reload? I don't think it refires the function on rotate

**Comment by odbol** [comment] 2015-12-07 01:47
I'm guessing this could be fixed by using CSS media queries instead of Javascript. Not sure if that's too much work or even possible though...

**Comment by dbox** [comment] 2015-12-08 05:52
@odbol I've been pondering if there is a way power everythig with [Element Queries](https://github.com/tysonmatanich/elementQuery), but I think the "magic" part - having the right-most elements drop to icons, is always going to require JS.

**Comment by dbox** [comment] 2015-12-09 02:44
So really this issue is "slow performance when having multiple instances of rrssb on the page." 

I'm definitely happy to look into ways to optimize the js calls, but not sure there is an immediate fix for this, as having lots of iterations on the page was never part of the original plan.

Closing for now. Will ponder for 2.0

**Closed by dbox** 2015-12-09 02:44 UTC
