### ISSUE TITLE
Chrome blocking popups

### ISSUE THREAD

**Issue by lombardicz** [kni-labs/rrssb#169] opened 2016-02-12 16:24 UTC
Hello,

I've been seeing the plugin blocked sometimes, seems to happen sometimes on second click or first, where it doesn't open a popup (it gets blocked) so it redirects to sharing page, breaking some uses.

Is anyone aware of this? Has Facebook changed some policy?

**Comment by dbox** [comment] 2016-02-12 16:24
dupe of #164

**Closed** 2016-02-12 16:25 UTC
