### ISSUE TITLE
Two Windows Pop Up With Twitter Button When Using Official Follow Button

### ISSUE THREAD

**Issue by MarioGiancini** [kni-labs/rrssb#181] opened 2016-07-21 21:09 UTC
Just want to point out that if you are using the twitter share button along side the official Twitter follow button, 2 windows will pop open when you click to share in most browsers.

The work around I found to fix this to use https://twitter.com/share? instead of https://twitter.com/intent/tweet? in the share button href. It seems to be calling something from Twitter's widget.js twice:

https://twittercommunity.com/t/tweet-web-intents-link-outputs-2-popup-windows-when-using-web-intents-js-and-profile-widget-at-the-same-time/17533

https://dev.twitter.com/web/javascript/loading

**Comment by dbox** [comment] 2016-07-22 13:08
Awesome. Nice sleuthing. Mind doing a pull request?

**Comment by dbox** [comment] 2016-10-12 15:24
I can't reproduce this and the official doc still has /intent as the proper url. Closing for now. Happy to reopen if something else pops up.

**Closed by dbox** 2016-10-12 15:24 UTC
